#!/bin/sh
if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.orion >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.orion=/luci-static/orion
		set luci.main.mediaurlbase=/luci-static/orion
		set luci.main.pollinterval='1'
		commit luci
	EOF
fi
exit 0